
name: CSS Generation

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
    
    - run: npm install

    - name: Run css file generation
      run: npm run -s build-css
      
    - name: Convert sample markdown to slides deck
      run: npm run -s generate-sample